[build]
  command = "npm run production"
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-html-validate"

  [plugins.inputs]
	ext = "html"
	config = ".htmlvalidate.json"

[[headers]]
  for = "/*"
  [headers.values]
	X-Frame-Options = "DENY"
	X-Content-Type-Options = "nosniff"
	Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/js/p.js"
  to = "https://plausible.io/js/script.js"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200
